### ISSUE TITLE
最新PC端微信2.4.1.79只能多开一个。

### ISSUE THREAD

**Issue by cfcboy** [anhkgg/multi_wechat_pc#1]
最新PC端微信2.4.1.79只能多开一个。加上原来的一共2个。
再双击多开就会弹出已经登陆的微信。
能不能改成，双击一次，多开一个。

**Comment by anhkgg** [comment]
不知道你什么系统，我这最新2.4.5.73依然可以正常无限多开，可否将问题描述清楚一点？
