### ISSUE TITLE
64位windows7上运行提示版本不兼容

### ISSUE THREAD

**Issue by liwangdong** [anhkgg/multi_wechat_pc#3]
![image](https://user-images.githubusercontent.com/9839208/34658772-c8825ba0-f46c-11e7-8cd1-c2ca06cc6830.png)
是已经激活的正版win7系统
![image](https://user-images.githubusercontent.com/9839208/34658789-fe82aeee-f46c-11e7-82ab-26fc9ad6c926.png)

**Comment by anhkgg** [comment]
可能是你下载的时候文件损坏，你比较一下md5是否和这个一致：
MD5: 4668DDA4B098A678C4C435573A0578C9

**Comment by liwangdong** [comment]
@anhkgg 谢谢，确实是文件问题。已解决，打扰了。
